### ISSUE TITLE
Userstory voor testen

### ISSUE THREAD

**Issue by miel775** [miel775/fix-the-flow-interactive-website#4]
**User story:** Als gebruiker wil ik filteren zodat ik een overzicht krijg van de schaduwplanten die ik zoek wanneer ik deze button indruk.

**Scenario:**  een bewoner in Amsterdam Oost is op zoek naar een nieuwe kamerplant voor in zijn woning maar twijfelt over zijn beslissing door de sorteerfunctie te gebruiken op de website kan hij makkelijker een keuze maken.

**Comment by Shannafdnd** [comment]
**User story feedback**

User story:
- Ik ben op zoek naar een nieuwe kamerplant. Door op het filter te klikken verschijnen plaatjes van kamerplanten. Ik heb alleen geen informatie over de planten, dus kiezen is een beetje moeilijk. 
- Ik twijfel over welke kamerplant ik wil. Door de sorteerfunctie te gebruiken zou het makkelijker zijn om een goeie kamerplant te vinden. Het filter werkt alleen nog niet dus dit is niet van toepassing. 

Feedback:
- Het filter was niet helemaal duidelijk, het was moeilijk te zien aan de knopjes waar ik op kon filteren. Het zou ook erg fijn zijn om de namen van de planten te zien. 

Je kan nog een user test doen als alles werkt, en deze feedback alvast gebruiken tijdens het verder bouwen.

**Comment by miel775** [comment]
![image](https://github.com/user-attachments/assets/52ca0ba6-2e92-4aae-9ad9-bb8dad3cc3ca)

**Comment by miel775** [comment]
Er is een andere interactie gebruikt, deze functie is geweerd uit de code.
